version: "3.9"
services:
  new-nebula:
    image: new-nebula
    command: --model-id EleutherAI/gpt-j-6B
    shm_size: 1g
    ports:
      - "7070:80"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [ gpu ]
